---
# Name your file secrets.yml
development:
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9009
  SESSION_SECRET: <your_secret_here>

test:
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9009
  SESSION_SECRET: <your_secret_here>

production:
  APP_HOST: toppop.herokuapp.com 
  API_HOST: toppop-api.herokuapp.com 
  SESSION_SECRET: <your_secret_here>