---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9090

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9090

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  ACCESS_TOKEN: <your_token_here>
  API_HOST: toppop-api.herokuapp.com