---
# Name your file secrets.yml

development:
<<<<<<< HEAD
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9090

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9090

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9090
=======
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9009
  SESSION_SECRET: <your_secret_here>

test:
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9009
  SESSION_SECRET: <your_secret_here>

production:
  APP_HOST: toppop.herokuapp.com 
  API_HOST: toppop-api.herokuapp.com 
  SESSION_SECRET: <your_secret_here>
>>>>>>> a2440d7d58116bd0838227d3a9b072554878a1ad
