---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9009
  REDISCLOUD_URL: <your_token_here>
  AWS_ACCESS_KEY_ID: <your_token_here>
  AWS_SECRET_ACCESS_KEY: <your_token_here>
  AWS_REGION: <region_name>
  QUEUE: <queue_name>
  QUEUE_URL: <set_by_AWS>

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9009
  REDISCLOUD_URL: <your_token_here>
  AWS_ACCESS_KEY_ID: <your_token_here>
  AWS_SECRET_ACCESS_KEY: <your_token_here>
  AWS_REGION: <region_name>
  QUEUE: <queue_name>
  QUEUE_URL: <set_by_AWS>

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  ACCESS_TOKEN: <your_token_here>
  API_HOST: https://toppop-api.herokuapp.com/
  REDISCLOUD_URL: <your_token_here>
  AWS_ACCESS_KEY_ID: <your_token_here>
  AWS_SECRET_ACCESS_KEY: <your_token_here>
  AWS_REGION: <region_name>
  QUEUE: <queue_name>
  QUEUE_URL: <set_by_AWS>
