---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: <url-assigned-by-Redis-provider-on-Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  QUEUE: <queue-name>
  QUEUE_URL: <set by AWS>

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  ACCESS_TOKEN: <your_token_here>
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: <url-assigned-by-Redis-provider-on-Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  QUEUE: <queue-name>
  QUEUE_URL: <set by AWS>

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  ACCESS_TOKEN: <your_token_here>
  API_HOST: https://toppop-api.herokuapp.com/
  REDISCLOUD_URL: <url-assigned-by-Redis-provider-on-Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  QUEUE: <queue-name>
  QUEUE_URL: <set by AWS>
